services:
  - type: web
    name: smart-travel-itinerary-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
